version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./desafio_api.db:/app/desafio_api.db
    networks:
      - mynetwork

networks:
  mynetwork:
